<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.shipshuk.bb.lib.api</groupId>
    <artifactId>bb-lib-api</artifactId>
    <version>1.0</version>
    <packaging>jar</packaging>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>26</maven.compiler.release>

    </properties>
    <dependencies>

        <dependency>
            <groupId>com.shipshuk.log.client</groupId>
            <artifactId>jax-log-client</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>com.shipshuk.entity</groupId>
            <artifactId>SHIPSHUK_DB</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>com.shipshuk.lib.util</groupId>
            <artifactId>jax-lib-util</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>com.shipshuk.lib.common</groupId>
            <artifactId>ss-lib-common</artifactId>
            <version>1.0</version>
        </dependency>

        <!-- EXTERNAL -->
        <dependency>
            <groupId>jakarta.persistence</groupId>
            <artifactId>jakarta.persistence-api</artifactId>
            <version>3.1.0</version>
            <scope>provided</scope>
        </dependency>
        
    </dependencies>

</project>

